version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/NuGet"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/src/npm"
    schedule:
      interval: "weekly"